#!/bin/sh

#==============================|Functions
CREATE_PKG(){
	pkg_name="$1"
	#Receiving the package name
	if tar -cvf ../${pkg_name};then
		printf '%s\n' "Package was created in ../${pkg_name}"
		return 0
	else
		printf '%s\n' "The package ${pkg_name} was not created..."
		exit 1
	fi
}
#==============================|Start
case "$1" in
	create|-c)
		#Downgrading to get package name
		#No package name? then get out...
		shift
		if [-z "$"]; then
			printf '%s\n' "You need to supply a package name"
			exit 1		
		fi
		CREATE_PKG "$@" 
		#Calling the function to create the package
	;;
esac

